feat(build): changing the golang version and fixing some error on build script

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -13,12 +13,12 @@ jobs:
                 os: [darwin, linux, windows]
                 arch: [amd64]
         steps:
-            - uses: actions/checkout@v2
+            - uses: actions/checkout@v4
 
             - name: Setup Go
-              uses: actions/setup-go@v2
+              uses: actions/setup-go@v5
               with:
-                  go-version: 1.23
+                  go-version: '1.22'
 
             - name: Build and Archive
               run: |
@@ -36,7 +36,7 @@ jobs:
               shell: bash
 
             - name: Upload Artifacts
-              uses: actions/upload-artifact@v3
+              uses: actions/upload-artifact@v4
               with:
                   name: GOWebServer-${{ matrix.os }}-${{ matrix.arch }}
                   path: GOWebServer-${{ matrix.os }}-${{ matrix.arch }}.zip
@@ -48,22 +48,22 @@ jobs:
         needs: build
         runs-on: ubuntu-latest
         steps:
-            - uses: actions/checkout@v2
+            - uses: actions/checkout@v4
             - name: Download Artifacts
-              uses: actions/download-artifact@v2
+              uses: actions/download-artifact@v4
 
             - name: Move Artifacts
               run: |
-                  mv GOWebServer-darwin-amd64/GOWebServer-darwin-amd64.zip .
-                  mv GOWebServer-linux-amd64/GOWebServer-linux-amd64.zip .
-                  mv GOWebServer-windows-amd64/GOWebServer-windows-amd64.zip .
+                  for file in GOWebServer-*/*.zip; do
+                    mv "$file" . || echo "Failed to move $file"
+                  done
 
             - name: Create Tag
               id: create_tag
               run: |
                   TAG_NAME=$(date +'%Y%m%d%H%M%S')-release
                   git tag $TAG_NAME
-                  echo "::set-output name=tag_name::$TAG_NAME"
+                  echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
               shell: bash
 
             - name: Upload Release Assets
@@ -72,11 +72,8 @@ jobs:
                   tag_name: ${{ steps.create_tag.outputs.tag_name }}
                   name: GOWebServer Release
                   files: |
-                      GOWebServer-darwin-386.zip
                       GOWebServer-darwin-amd64.zip
-                      GOWebServer-linux-386.zip
                       GOWebServer-linux-amd64.zip
-                      GOWebServer-windows-386.zip
                       GOWebServer-windows-amd64.zip
                   draft: false
                   prerelease: false
